# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.weapon_type_response_inner import WeaponTypeResponseInner

class TestWeaponTypeResponseInner(unittest.TestCase):
    """WeaponTypeResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeaponTypeResponseInner:
        """Test WeaponTypeResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeaponTypeResponseInner`
        """
        model = WeaponTypeResponseInner()
        if include_optional:
            return WeaponTypeResponseInner(
                weapon_type = '',
                weapon_type_name = ''
            )
        else:
            return WeaponTypeResponseInner(
        )
        """

    def testWeaponTypeResponseInner(self):
        """Test WeaponTypeResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
