# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.acquisition_detail_response_inner import AcquisitionDetailResponseInner

class TestAcquisitionDetailResponseInner(unittest.TestCase):
    """AcquisitionDetailResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AcquisitionDetailResponseInner:
        """Test AcquisitionDetailResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AcquisitionDetailResponseInner`
        """
        model = AcquisitionDetailResponseInner()
        if include_optional:
            return AcquisitionDetailResponseInner(
                acquisition_detail_id = '',
                acquisition_detail_name = ''
            )
        else:
            return AcquisitionDetailResponseInner(
        )
        """

    def testAcquisitionDetailResponseInner(self):
        """Test AcquisitionDetailResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
