# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.customizing_item_response_inner_customizing_item_evolution_stage_inner import CustomizingItemResponseInnerCustomizingItemEvolutionStageInner

class TestCustomizingItemResponseInnerCustomizingItemEvolutionStageInner(unittest.TestCase):
    """CustomizingItemResponseInnerCustomizingItemEvolutionStageInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomizingItemResponseInnerCustomizingItemEvolutionStageInner:
        """Test CustomizingItemResponseInnerCustomizingItemEvolutionStageInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomizingItemResponseInnerCustomizingItemEvolutionStageInner`
        """
        model = CustomizingItemResponseInnerCustomizingItemEvolutionStageInner()
        if include_optional:
            return CustomizingItemResponseInnerCustomizingItemEvolutionStageInner(
                stage = 1.337,
                customizing_item_image_url = ''
            )
        else:
            return CustomizingItemResponseInnerCustomizingItemEvolutionStageInner(
        )
        """

    def testCustomizingItemResponseInnerCustomizingItemEvolutionStageInner(self):
        """Test CustomizingItemResponseInnerCustomizingItemEvolutionStageInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
