# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.core_type_response_inner_core_option_inner_available_item_option_inner import CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner

class TestCoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner(unittest.TestCase):
    """CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner:
        """Test CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner`
        """
        model = CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner()
        if include_optional:
            return CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner(
                item_option = '',
                option_type = '',
                option_grade = '',
                option_effect = tfd_metadata_client.models.core_type_response_inner_core_option_inner_available_item_option_inner_option_effect.CoreTypeResponse_inner_core_option_inner_available_item_option_inner_option_effect(
                    stat_id = '', 
                    operator_type = '', 
                    min_stat_value = 1.337, 
                    max_stat_value = 1.337, ),
                rate = 1.337
            )
        else:
            return CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner(
        )
        """

    def testCoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner(self):
        """Test CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
