# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.core_slot_response_inner import CoreSlotResponseInner

class TestCoreSlotResponseInner(unittest.TestCase):
    """CoreSlotResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreSlotResponseInner:
        """Test CoreSlotResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreSlotResponseInner`
        """
        model = CoreSlotResponseInner()
        if include_optional:
            return CoreSlotResponseInner(
                core_slot_id = '',
                available_weapon_id = [
                    ''
                    ],
                available_external_component_id = [
                    ''
                    ],
                available_core_type = [
                    ''
                    ]
            )
        else:
            return CoreSlotResponseInner(
        )
        """

    def testCoreSlotResponseInner(self):
        """Test CoreSlotResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
