# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.api.meta_data_api import MetaDataApi


class TestMetaDataApi(unittest.TestCase):
    """MetaDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaDataApi()

    def tearDown(self) -> None:
        pass

    def test_static_tfd_meta_adapt_level_json_get(self) -> None:
        """Test case for static_tfd_meta_adapt_level_json_get

        Retrieve adaptability level metadata
        """
        pass

    def test_static_tfd_meta_amorphous_reward_json_get(self) -> None:
        """Test case for static_tfd_meta_amorphous_reward_json_get

        Retrieve Amorphous Material open reward metadata
        """
        pass

    def test_static_tfd_meta_arche_tuning_board_group_json_get(self) -> None:
        """Test case for static_tfd_meta_arche_tuning_board_group_json_get

        Retrieve Arche tuning board group metadata
        """
        pass

    def test_static_tfd_meta_arche_tuning_board_json_get(self) -> None:
        """Test case for static_tfd_meta_arche_tuning_board_json_get

        Retrieve Arche tuning board metadata
        """
        pass

    def test_static_tfd_meta_core_slot_json_get(self) -> None:
        """Test case for static_tfd_meta_core_slot_json_get

        Retrieve core slot metadata
        """
        pass

    def test_static_tfd_meta_descendant_level_detail_json_get(self) -> None:
        """Test case for static_tfd_meta_descendant_level_detail_json_get

        Retrieve EXP metadata by descendant level
        """
        pass

    def test_static_tfd_meta_fellow_level_detail_json_get(self) -> None:
        """Test case for static_tfd_meta_fellow_level_detail_json_get

        Retrieve EXP metadata by fellow level
        """
        pass

    def test_static_tfd_meta_language_code_acquisition_detail_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_acquisition_detail_json_get

        Retrieve acquisition source info metadata
        """
        pass

    def test_static_tfd_meta_language_code_amorphous_open_condition_description_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_amorphous_open_condition_description_json_get

        Retrieve Amorphous Material opening location metadata
        """
        pass

    def test_static_tfd_meta_language_code_arche_tuning_node_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_arche_tuning_node_json_get

        Retrieve Arche tuning node metadata
        """
        pass

    def test_static_tfd_meta_language_code_consumable_material_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_consumable_material_json_get

        Retrieve consumable items metadata
        """
        pass

    def test_static_tfd_meta_language_code_core_type_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_core_type_json_get

        Retrieve core type metadata
        """
        pass

    def test_static_tfd_meta_language_code_customizing_item_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_customizing_item_json_get

        Retrieve customization item metadata
        """
        pass

    def test_static_tfd_meta_language_code_descendant_group_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_descendant_group_json_get

        Retrieve descendant group metadata
        """
        pass

    def test_static_tfd_meta_language_code_descendant_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_descendant_json_get

        Retrieve descendant metadata
        """
        pass

    def test_static_tfd_meta_language_code_external_component_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_external_component_json_get

        Retrieve external component metadata
        """
        pass

    def test_static_tfd_meta_language_code_fellow_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_fellow_json_get

        Retrieve fellow metadata
        """
        pass

    def test_static_tfd_meta_language_code_medal_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_medal_json_get

        Retrieve medal meta data
        """
        pass

    def test_static_tfd_meta_language_code_module_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_module_json_get

        Retrieve module metadata
        """
        pass

    def test_static_tfd_meta_language_code_reactor_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_reactor_json_get

        Retrieve Reactor metadata
        """
        pass

    def test_static_tfd_meta_language_code_research_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_research_json_get

        Retrieve research info metadata
        """
        pass

    def test_static_tfd_meta_language_code_reward_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_reward_json_get

        Retrieve Difficulty Level Rewards metadata
        """
        pass

    def test_static_tfd_meta_language_code_stat_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_stat_json_get

        Retrieve base stat metadata
        """
        pass

    def test_static_tfd_meta_language_code_tier_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_tier_json_get

        Retrieve tier metadata
        """
        pass

    def test_static_tfd_meta_language_code_title_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_title_json_get

        Retrieve Title metadata
        """
        pass

    def test_static_tfd_meta_language_code_void_battle_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_void_battle_json_get

        Retrieve Void Intercept Battle metadata
        """
        pass

    def test_static_tfd_meta_language_code_weapon_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_weapon_json_get

        Retrieve weapon metadata
        """
        pass

    def test_static_tfd_meta_language_code_weapon_type_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_weapon_type_json_get

        Retrieve weapon type metadata
        """
        pass

    def test_static_tfd_meta_mastery_rank_level_detail_json_get(self) -> None:
        """Test case for static_tfd_meta_mastery_rank_level_detail_json_get

        Retrieve EXP metadata by Mastery Rank
        """
        pass


if __name__ == '__main__':
    unittest.main()
