# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.amorphous_reward_response_inner_open_reward_inner import AmorphousRewardResponseInnerOpenRewardInner

class TestAmorphousRewardResponseInnerOpenRewardInner(unittest.TestCase):
    """AmorphousRewardResponseInnerOpenRewardInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AmorphousRewardResponseInnerOpenRewardInner:
        """Test AmorphousRewardResponseInnerOpenRewardInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AmorphousRewardResponseInnerOpenRewardInner`
        """
        model = AmorphousRewardResponseInnerOpenRewardInner()
        if include_optional:
            return AmorphousRewardResponseInnerOpenRewardInner(
                reward_type = '',
                required_stabilizer = '',
                reward_item = [
                    tfd_metadata_client.models.amorphous_reward_response_inner_open_reward_inner_reward_item_inner.AmorphousRewardResponse_inner_open_reward_inner_reward_item_inner(
                        meta_type = '', 
                        meta_id = '', 
                        rate = 1.337, )
                    ]
            )
        else:
            return AmorphousRewardResponseInnerOpenRewardInner(
        )
        """

    def testAmorphousRewardResponseInnerOpenRewardInner(self):
        """Test AmorphousRewardResponseInnerOpenRewardInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
