# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.consumable_material_response_inner import ConsumableMaterialResponseInner

class TestConsumableMaterialResponseInner(unittest.TestCase):
    """ConsumableMaterialResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsumableMaterialResponseInner:
        """Test ConsumableMaterialResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsumableMaterialResponseInner`
        """
        model = ConsumableMaterialResponseInner()
        if include_optional:
            return ConsumableMaterialResponseInner(
                consumable_material_id = '',
                image_url = '',
                consumable_material_name = '',
                required_mastery_rank_level = 1.337,
                material_type = '',
                acquisition_detail = [
                    ''
                    ],
                amorphous_reward = [
                    ''
                    ],
                amorphous_open_condition = [
                    ''
                    ]
            )
        else:
            return ConsumableMaterialResponseInner(
        )
        """

    def testConsumableMaterialResponseInner(self):
        """Test ConsumableMaterialResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
