# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.core_type_response_inner_core_option_inner_available_item_option_inner_option_effect import CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect

class TestCoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect(unittest.TestCase):
    """CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect:
        """Test CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect`
        """
        model = CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect()
        if include_optional:
            return CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect(
                stat_id = '',
                operator_type = '',
                min_stat_value = 1.337,
                max_stat_value = 1.337
            )
        else:
            return CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect(
        )
        """

    def testCoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect(self):
        """Test CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
