# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.research_response_inner_research_cost_inner import ResearchResponseInnerResearchCostInner

class TestResearchResponseInnerResearchCostInner(unittest.TestCase):
    """ResearchResponseInnerResearchCostInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResearchResponseInnerResearchCostInner:
        """Test ResearchResponseInnerResearchCostInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResearchResponseInnerResearchCostInner`
        """
        model = ResearchResponseInnerResearchCostInner()
        if include_optional:
            return ResearchResponseInnerResearchCostInner(
                currency_type = '',
                currency_value = 1.337
            )
        else:
            return ResearchResponseInnerResearchCostInner(
        )
        """

    def testResearchResponseInnerResearchCostInner(self):
        """Test ResearchResponseInnerResearchCostInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
