# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.arche_tuning_board_response_inner import ArcheTuningBoardResponseInner

class TestArcheTuningBoardResponseInner(unittest.TestCase):
    """ArcheTuningBoardResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArcheTuningBoardResponseInner:
        """Test ArcheTuningBoardResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArcheTuningBoardResponseInner`
        """
        model = ArcheTuningBoardResponseInner()
        if include_optional:
            return ArcheTuningBoardResponseInner(
                arche_tuning_board_id = '',
                row_size = 1.337,
                column_size = 1.337,
                node = [
                    tfd_metadata_client.models.arche_tuning_board_response_inner_node_inner.ArcheTuningBoardResponse_inner_node_inner(
                        node_id = '', 
                        position_row = 1.337, 
                        position_column = 1.337, )
                    ]
            )
        else:
            return ArcheTuningBoardResponseInner(
        )
        """

    def testArcheTuningBoardResponseInner(self):
        """Test ArcheTuningBoardResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
