# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.adapt_level_response_inner import AdaptLevelResponseInner

class TestAdaptLevelResponseInner(unittest.TestCase):
    """AdaptLevelResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdaptLevelResponseInner:
        """Test AdaptLevelResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdaptLevelResponseInner`
        """
        model = AdaptLevelResponseInner()
        if include_optional:
            return AdaptLevelResponseInner(
                level = 1.337,
                exp_per_level = 1.337
            )
        else:
            return AdaptLevelResponseInner(
        )
        """

    def testAdaptLevelResponseInner(self):
        """Test AdaptLevelResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
