# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.arche_tuning_node_response_inner_node_effect_inner import ArcheTuningNodeResponseInnerNodeEffectInner

class TestArcheTuningNodeResponseInnerNodeEffectInner(unittest.TestCase):
    """ArcheTuningNodeResponseInnerNodeEffectInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArcheTuningNodeResponseInnerNodeEffectInner:
        """Test ArcheTuningNodeResponseInnerNodeEffectInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArcheTuningNodeResponseInnerNodeEffectInner`
        """
        model = ArcheTuningNodeResponseInnerNodeEffectInner()
        if include_optional:
            return ArcheTuningNodeResponseInnerNodeEffectInner(
                stat_id = '',
                stat_value = 1.337,
                operator_type = ''
            )
        else:
            return ArcheTuningNodeResponseInnerNodeEffectInner(
        )
        """

    def testArcheTuningNodeResponseInnerNodeEffectInner(self):
        """Test ArcheTuningNodeResponseInnerNodeEffectInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
