# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.customizing_item_response_inner import CustomizingItemResponseInner

class TestCustomizingItemResponseInner(unittest.TestCase):
    """CustomizingItemResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomizingItemResponseInner:
        """Test CustomizingItemResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomizingItemResponseInner`
        """
        model = CustomizingItemResponseInner()
        if include_optional:
            return CustomizingItemResponseInner(
                customizing_item_id = '',
                customizing_item_name = '',
                customizing_item_type = '',
                customizing_item_tier_id = '',
                customizing_item_description = '',
                customizing_item_image_url = '',
                customizing_item_evolution_stage = [
                    tfd_metadata_client.models.customizing_item_response_inner_customizing_item_evolution_stage_inner.CustomizingItemResponse_inner_customizing_item_evolution_stage_inner(
                        stage = 1.337, 
                        customizing_item_image_url = '', )
                    ],
                available_descendant = [
                    ''
                    ]
            )
        else:
            return CustomizingItemResponseInner(
        )
        """

    def testCustomizingItemResponseInner(self):
        """Test CustomizingItemResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
