# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_metadata_client.models.medal_response_inner_medal_detail_inner import MedalResponseInnerMedalDetailInner

class TestMedalResponseInnerMedalDetailInner(unittest.TestCase):
    """MedalResponseInnerMedalDetailInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MedalResponseInnerMedalDetailInner:
        """Test MedalResponseInnerMedalDetailInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MedalResponseInnerMedalDetailInner`
        """
        model = MedalResponseInnerMedalDetailInner()
        if include_optional:
            return MedalResponseInnerMedalDetailInner(
                medal_level = 1.337,
                medal_name = '',
                medal_tier_id = '',
                medal_image_url = ''
            )
        else:
            return MedalResponseInnerMedalDetailInner(
        )
        """

    def testMedalResponseInnerMedalDetailInner(self):
        """Test MedalResponseInnerMedalDetailInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
