# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tfd_metadata_client.models.amorphous_reward_response_inner_open_reward_inner_reward_item_inner import AmorphousRewardResponseInnerOpenRewardInnerRewardItemInner
from typing import Optional, Set
from typing_extensions import Self

class AmorphousRewardResponseInnerOpenRewardInner(BaseModel):
    """
    AmorphousRewardResponseInnerOpenRewardInner
    """ # noqa: E501
    reward_type: Optional[StrictStr] = Field(default=None, description="Reward type (Default, Upgrade)")
    required_stabilizer: Optional[StrictStr] = Field(default=None, description="Identifier of the Shape Stabilizer required for upgrade (refer to /meta/consumable-material API)")
    reward_item: Optional[List[AmorphousRewardResponseInnerOpenRewardInnerRewardItemInner]] = Field(default=None, description="Information about items from Amorphous Material open rewards")
    __properties: ClassVar[List[str]] = ["reward_type", "required_stabilizer", "reward_item"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AmorphousRewardResponseInnerOpenRewardInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reward_item (list)
        _items = []
        if self.reward_item:
            for _item_reward_item in self.reward_item:
                if _item_reward_item:
                    _items.append(_item_reward_item.to_dict())
            _dict['reward_item'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AmorphousRewardResponseInnerOpenRewardInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reward_type": obj.get("reward_type"),
            "required_stabilizer": obj.get("required_stabilizer"),
            "reward_item": [AmorphousRewardResponseInnerOpenRewardInnerRewardItemInner.from_dict(_item) for _item in obj["reward_item"]] if obj.get("reward_item") is not None else None
        })
        return _obj


