# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from tfd_metadata_client.models.arche_tuning_node_response_inner_node_effect_inner import ArcheTuningNodeResponseInnerNodeEffectInner
from typing import Optional, Set
from typing_extensions import Self

class ArcheTuningNodeResponseInner(BaseModel):
    """
    ArcheTuningNodeResponseInner
    """ # noqa: E501
    node_id: Optional[StrictStr] = Field(default=None, description="Node identifier")
    node_name: Optional[StrictStr] = Field(default=None, description="Node name")
    node_image_url: Optional[StrictStr] = Field(default=None, description="Node image URL")
    node_type: Optional[StrictStr] = Field(default=None, description="Node type")
    tier_id: Optional[StrictStr] = Field(default=None, description="Node tier identifier (Refer to /meta/tier API)")
    required_tuning_point: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Required points")
    node_effect: Optional[List[ArcheTuningNodeResponseInnerNodeEffectInner]] = None
    __properties: ClassVar[List[str]] = ["node_id", "node_name", "node_image_url", "node_type", "tier_id", "required_tuning_point", "node_effect"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArcheTuningNodeResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in node_effect (list)
        _items = []
        if self.node_effect:
            for _item_node_effect in self.node_effect:
                if _item_node_effect:
                    _items.append(_item_node_effect.to_dict())
            _dict['node_effect'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArcheTuningNodeResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "node_id": obj.get("node_id"),
            "node_name": obj.get("node_name"),
            "node_image_url": obj.get("node_image_url"),
            "node_type": obj.get("node_type"),
            "tier_id": obj.get("tier_id"),
            "required_tuning_point": obj.get("required_tuning_point"),
            "node_effect": [ArcheTuningNodeResponseInnerNodeEffectInner.from_dict(_item) for _item in obj["node_effect"]] if obj.get("node_effect") is not None else None
        })
        return _obj


