# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from tfd_metadata_client.models.core_type_response_inner_core_option_inner_available_item_option_inner_option_effect import CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect
from typing import Optional, Set
from typing_extensions import Self

class CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner(BaseModel):
    """
    CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner
    """ # noqa: E501
    item_option: Optional[StrictStr] = Field(default=None, description="Option name")
    option_type: Optional[StrictStr] = Field(default=None, description="Option category")
    option_grade: Optional[StrictStr] = Field(default=None, description="Option grade<br>- Higher grades provide better effect values.")
    option_effect: Optional[CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect] = None
    rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Probability of the option appearing")
    __properties: ClassVar[List[str]] = ["item_option", "option_type", "option_grade", "option_effect", "rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of option_effect
        if self.option_effect:
            _dict['option_effect'] = self.option_effect.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_option": obj.get("item_option"),
            "option_type": obj.get("option_type"),
            "option_grade": obj.get("option_grade"),
            "option_effect": CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect.from_dict(obj["option_effect"]) if obj.get("option_effect") is not None else None,
            "rate": obj.get("rate")
        })
        return _obj


