# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tfd_metadata_client.models.core_type_response_inner_core_option_inner_available_item_option_inner import CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner
from tfd_metadata_client.models.core_type_response_inner_core_option_inner_detail_inner import CoreTypeResponseInnerCoreOptionInnerDetailInner
from typing import Optional, Set
from typing_extensions import Self

class CoreTypeResponseInnerCoreOptionInner(BaseModel):
    """
    CoreTypeResponseInnerCoreOptionInner
    """ # noqa: E501
    core_option_id: Optional[StrictStr] = Field(default=None, description="core type option identifier")
    detail: Optional[List[CoreTypeResponseInnerCoreOptionInnerDetailInner]] = Field(default=None, description="Detailed information on core type options")
    available_item_option: Optional[List[CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner]] = Field(default=None, description="Item options")
    __properties: ClassVar[List[str]] = ["core_option_id", "detail", "available_item_option"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreTypeResponseInnerCoreOptionInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in detail (list)
        _items = []
        if self.detail:
            for _item_detail in self.detail:
                if _item_detail:
                    _items.append(_item_detail.to_dict())
            _dict['detail'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_item_option (list)
        _items = []
        if self.available_item_option:
            for _item_available_item_option in self.available_item_option:
                if _item_available_item_option:
                    _items.append(_item_available_item_option.to_dict())
            _dict['available_item_option'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreTypeResponseInnerCoreOptionInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "core_option_id": obj.get("core_option_id"),
            "detail": [CoreTypeResponseInnerCoreOptionInnerDetailInner.from_dict(_item) for _item in obj["detail"]] if obj.get("detail") is not None else None,
            "available_item_option": [CoreTypeResponseInnerCoreOptionInnerAvailableItemOptionInner.from_dict(_item) for _item in obj["available_item_option"]] if obj.get("available_item_option") is not None else None
        })
        return _obj


