# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tfd_metadata_client.models.customizing_item_response_inner_customizing_item_evolution_stage_inner import CustomizingItemResponseInnerCustomizingItemEvolutionStageInner
from typing import Optional, Set
from typing_extensions import Self

class CustomizingItemResponseInner(BaseModel):
    """
    CustomizingItemResponseInner
    """ # noqa: E501
    customizing_item_id: Optional[StrictStr] = Field(default=None, description="Customization item identifier")
    customizing_item_name: Optional[StrictStr] = Field(default=None, description="Customization item name")
    customizing_item_type: Optional[StrictStr] = Field(default=None, description="Customization item type")
    customizing_item_tier_id: Optional[StrictStr] = Field(default=None, description="Customization item tier (Refer to /meta/tier API)")
    customizing_item_description: Optional[StrictStr] = Field(default=None, description="Customization item description")
    customizing_item_image_url: Optional[StrictStr] = Field(default=None, description="Customization item image path")
    customizing_item_evolution_stage: Optional[List[CustomizingItemResponseInnerCustomizingItemEvolutionStageInner]] = Field(default=None, description="Evolution stage information of the customization item")
    available_descendant: Optional[List[StrictStr]] = Field(default=None, description="Applicable descendant list (Refer to /meta/descendant API)")
    __properties: ClassVar[List[str]] = ["customizing_item_id", "customizing_item_name", "customizing_item_type", "customizing_item_tier_id", "customizing_item_description", "customizing_item_image_url", "customizing_item_evolution_stage", "available_descendant"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomizingItemResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in customizing_item_evolution_stage (list)
        _items = []
        if self.customizing_item_evolution_stage:
            for _item_customizing_item_evolution_stage in self.customizing_item_evolution_stage:
                if _item_customizing_item_evolution_stage:
                    _items.append(_item_customizing_item_evolution_stage.to_dict())
            _dict['customizing_item_evolution_stage'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomizingItemResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customizing_item_id": obj.get("customizing_item_id"),
            "customizing_item_name": obj.get("customizing_item_name"),
            "customizing_item_type": obj.get("customizing_item_type"),
            "customizing_item_tier_id": obj.get("customizing_item_tier_id"),
            "customizing_item_description": obj.get("customizing_item_description"),
            "customizing_item_image_url": obj.get("customizing_item_image_url"),
            "customizing_item_evolution_stage": [CustomizingItemResponseInnerCustomizingItemEvolutionStageInner.from_dict(_item) for _item in obj["customizing_item_evolution_stage"]] if obj.get("customizing_item_evolution_stage") is not None else None,
            "available_descendant": obj.get("available_descendant")
        })
        return _obj


