# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tfd_metadata_client.models.fellow_response_inner_fellow_detail_inner import FellowResponseInnerFellowDetailInner
from typing import Optional, Set
from typing_extensions import Self

class FellowResponseInner(BaseModel):
    """
    FellowResponseInner
    """ # noqa: E501
    fellow_id: Optional[StrictStr] = Field(default=None, description="Identifier for the fellow")
    fellow_name: Optional[StrictStr] = Field(default=None, description="Fellow name")
    fellow_tier_id: Optional[StrictStr] = Field(default=None, description="Fellow level (refer to /meta/tier API)")
    fellow_detail: Optional[List[FellowResponseInnerFellowDetailInner]] = Field(default=None, description="Details by fellow level")
    __properties: ClassVar[List[str]] = ["fellow_id", "fellow_name", "fellow_tier_id", "fellow_detail"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FellowResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in fellow_detail (list)
        _items = []
        if self.fellow_detail:
            for _item_fellow_detail in self.fellow_detail:
                if _item_fellow_detail:
                    _items.append(_item_fellow_detail.to_dict())
            _dict['fellow_detail'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FellowResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fellow_id": obj.get("fellow_id"),
            "fellow_name": obj.get("fellow_name"),
            "fellow_tier_id": obj.get("fellow_tier_id"),
            "fellow_detail": [FellowResponseInnerFellowDetailInner.from_dict(_item) for _item in obj["fellow_detail"]] if obj.get("fellow_detail") is not None else None
        })
        return _obj


